### ISSUE TITLE
"mut_mat" variable definination 

### ISSUE THREAD

**Issue by shirleydaidai** [CuppenResearch/MutationalPatterns#6]
I cannot find "mut_mat" variable defined in the whole script. Could you point me to that? Thanks.

```
# Add a tiny psuedocount to avoid a 0 in the matrix.
  mut_mat = mut_mat + 0.0001
```

**Comment by roelj** [comment]
Hi!  The `mut_mat` variable is created using the `mut_matrix` function, as described in the section titled "96 Mutation profile":
```
mut_mat <- mut_matrix(vcf_list = vcfs, ref_genome = ref_genome)
```

Please note that `mut_mat` could be called anything else, as `mut_mat` is just a variable name, not a special one defined by this package.

Hope this helps.  Otherwise, please let me know.

**Comment by shirleydaidai** [comment]
But I used the same code and got a different plot.
![image](https://cloud.githubusercontent.com/assets/20200043/20591803/5f9b9722-b265-11e6-97ca-9e674f1d1141.png)

**Comment by roelj** [comment]
So, what data are you using, what are you trying to do, and how would you expect your data to look like?

**Comment by shirleydaidai** [comment]
I'm trying to repeat the results and used the same data and code in README.md file.

**Comment by shirleydaidai** [comment]
Well. I found this is the same as that in vignette.
